apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-arbeidsforhold-api
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-arbeidsforhold-api/internal/isalive
    initialDelay: 10
  readiness:
    path: /tms-arbeidsforhold-api/internal/isready
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-arbeidsforhold-api/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.ansatt.nav.no/tms-arbeidsforhold-api"
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pdl-mottak.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: institusjon-opphold-proxy.prod-fss-pub.nais.io
        - host: medlemskap-medl-api.prod-fss-pub.nais.io
        - host: ereg-services.prod-fss-pub.nais.io
        - host: sporingslogg.prod-fss-pub.nais.io
      rules:
        - application: "digdir-krr-proxy"
          namespace: "team-rocket"
        - application: "kodeverk-api"
          namespace: "team-rocket"
        - application: "sokos-kontoregister-person"
          namespace: "okonomi"
        - application: "norg2"
          namespace: "org"
  secureLogs:
    enabled: true
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 20m
      memory: 256Mi
  env:
    - name: EREG_SERVICES_URL
      value: https://ereg-services.prod-fss-pub.nais.io
    - name: AAREG_SERVICES_URL
      value: https://aareg-services.prod-fss-pub.nais.io
    - name: AAREG_CLIENT_ID
      value: prod-fss:arbeidsforhold:aareg-services-nais
